---
- hosts: "{{ target | default('localhost')}}"
  become: yes
  roles:
    - role: ansible-role-nvm-f
      nvm_commands:
       - "nvm exec default npm install"
      become: true            # THIS WILL CHANGE THE LOGIN CONTEXT TO USE THE USER BELOW
      become_user: ec2-user   # THIS INSTALLS NVM IN THE CONTEXT OF THE EC2-USER/DEFAULT USER