---
# tasks file for nodejs

- name: Upgrade all packages
  yum:
    name: '*'
    state: latest
- name: Installing nodejs & npm 
  yum:
    name: "{{item}}"
    state: installed 
  with_items:
    - nodejs
    - npm