---
# tasks file for nodejs
- name: "Install node version manager (nvm)"
  shell: curl -sL https://rpm.nodesource.com/setup_10.x | sudo bash -
  become: yes
- name: "Use nvm to install the latest version of Node.js"
  shell: yum install node
  become: yes

  



