---
# tasks file for nodejs
- name: "Install node version manager (nvm)"
  shell: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
- name: "Activate nvm"
  shell: . ~/.nvm/nvm.sh
- name: "Use nvm to install the latest version of Node.js"
  shell: nvm install node
  become: yes
  args:
    executable: /usr/sbin
  



